defaults:
  - etc
  - cnn_ctc
  - _self_

trainer: CTCTrainer
predict_onsets_and_frets: false 
predict_tab: true
predict_notes: true

model:
  predict_notes_blank: true # For MCTC
  output_notes:
    activation: 'log_softmax' # For MCTC
  fc_string_block_tab:
    activation: log_softmax
    in_channels: 96

data:
  sequence: True
  load_notes: ${predict_notes}
  
criterions:
  notes:
    name: MCTC
    config: 
      reduction: "sum"
      experimental_flatten_batch: false
  criterion_weights: [0.9, 0.1]

